# Generated by Django 3.1.12 on 2025-04-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otpvalidation',
            table='signup_validation',
        ),
        migrations.AlterModelTable(
            name='user',
            table='signup_user',
        ),
    ]
